name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: my-step2
        run: make install
      - name: my-Lint
        run: make lint
      - name: my-Test 
        run: make test
        
